language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "e688c44d64f7ab2db0513b2f1ffe600ebbdeb4ab"
jdk:
  - oraclejdk8
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

before_script: 
    - chmod +x gradlew
    
script:
  # runs all junit tests and creates a coverage report
  - ./gradlew clean jacocoTestReport --stacktrace
    
after_success:
  # upload project with coverage report to sonarqube
  - ./gradlew sonarqube --stacktrace